### ISSUE TITLE
Please remove the duplicate file from origin repo

### ISSUE THREAD

**Issue by VarshneyaAmit** [amyvrm/oss_ass4_grp5#24]
Kindly review below file and remove it as this is duplicated file.

![image](https://user-images.githubusercontent.com/70054616/114903424-6da5c300-9e34-11eb-85b7-0f46417dc4e2.png)

**Comment by VarshneyaAmit** [comment]
Thanks for taking the quick action. It seems fixed now.

**Comment by amyvrm** [comment]
Thank you, this is helpfull.
